sudo: false
language: python
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip install -r test-requirements.txt --download-cache $HOME/.pip-cache
script: nosetests -v -l DEBUG --logging-level=DEBUG
services:
  - rabbitmq
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 3.6
    tags: true
    all_branches: true
  password:
    secure: "aNHNT5H3H2TztkKDmF/aWEANMNG+YxonL4HPSCfixx56xauT8oxShARw47Tb8QvhThhHmJAcwc93N1HwCqqFLxQN6eqGsZgV5ir1RRuJmSzAuxdx1wtVtY67ncBFlGUbH0H7yuwlVOYv3Rs7GA0gArOqSotdSV85Yun8EmuN5Q0="
cache:
  directories:
    - $HOME/.pip-cache/
